kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: rust:latest
    volumes:
      - name: cache
        path: /tmp/cache
    commands:
      - apt-get update
      - apt-get -y upgrade
      - apt-get -y install zstd curl g++-8
      - cp /tmp/cache/wiki_ts_200M_uint64 tests/
      - cp /tmp/cache/osm_cellids_200M_uint64 tests/
      - cd tests
      - make -j 2

volumes:
  - name: cache
    host:
      path: /media/Berrik/sosd_cache
